namespace BindMapper;

/// <summary>
/// High-performance, compile-time object mapper powered by Roslyn Source Generators.
/// All mapping methods are generated at compile-time based on [MapperConfiguration] attributes.
/// </summary>
/// <remarks>
/// <para><strong>⚡ All methods are 100% Source Generator-driven - Zero runtime overhead.</strong></para>
/// <para><strong>Usage:</strong></para>
/// <code>
/// // Single object mapping
/// var dto = Mapper.To&lt;UserDto&gt;(user);
/// 
/// // Collection mapping
/// var list = Mapper.ToList&lt;UserDto&gt;(users);
/// var array = Mapper.ToArray&lt;UserDto&gt;(users);
/// var enumerable = Mapper.ToEnumerable&lt;UserDto&gt;(users);
/// var collection = Mapper.ToCollection&lt;UserDto&gt;(users);
/// 
/// // Span mapping (zero-allocation)
/// var span = Mapper.ToSpan&lt;UserDto&gt;(sourceSpan);
/// </code>
/// <para><strong>Configuration:</strong></para>
/// <code>
/// [MapperConfiguration]
/// public static void Configure()
/// {
///     MapperSetup.CreateMap&lt;User, UserDto&gt;();
/// }
/// </code>
/// <para>
/// ⚡ Performance: ~12ns per mapping (Intel Core i5-14600KF, .NET 10)<br/>
/// ✅ Zero reflection<br/>
/// ✅ Fully inlined<br/>
/// ✅ AOT-compatible<br/>
/// ✅ Trim-safe<br/>
/// </para>
/// </remarks>
public static partial class Mapper
{
    // ╔════════════════════════════════════════════════════════════════════╗
    // ║  ALL METHODS ARE GENERATED BY SOURCE GENERATOR (MapperGenerator)   ║
    // ║  No manual implementation - Pure compile-time code generation      ║
    // ╚════════════════════════════════════════════════════════════════════╝
    
    // Generated methods (see MapperCodeGenerator.cs):
    // 
    // ┌─────────────────────────────────────────────────────────────────┐
    // │  Single Object Mapping                                          │
    // └─────────────────────────────────────────────────────────────────┘
    // public static TDestination To<TDestination>(object source)
    //
    // ┌─────────────────────────────────────────────────────────────────┐
    // │  Collection Mapping                                             │
    // └─────────────────────────────────────────────────────────────────┘
    // public static List<TDestination> ToList<TDestination>(object? source)
    // public static TDestination[] ToArray<TDestination>(object? source)
    // public static IEnumerable<TDestination> ToEnumerable<TDestination>(object? source)
    // public static Collection<TDestination> ToCollection<TDestination>(object? source)
    //
    // ┌─────────────────────────────────────────────────────────────────┐
    // │  Span Mapping (Zero-Allocation)                                 │
    // └─────────────────────────────────────────────────────────────────┘
    // public static TDestination[] ToSpan<TDestination>(ReadOnlySpan<object> source)
}

