name: 🐛 Bug Report
description: Reportar um problema ou comportamento inesperado
title: "[Bug]: "
labels: ["bug", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        Obrigado por reportar um bug! Por favor, preencha o formulário abaixo para nos ajudar a entender e reproduzir o problema.
  
  - type: textarea
    id: description
    attributes:
      label: Descrição do Bug
      description: Uma descrição clara e concisa do que é o bug.
      placeholder: Quando eu faço X, esperava Y, mas acontece Z...
    validations:
      required: true
  
  - type: textarea
    id: reproduction
    attributes:
      label: Passos para Reproduzir
      description: Como podemos reproduzir o problema?
      placeholder: |
        1. Configure o mapper com...
        2. Chame o método...
        3. Observe o erro...
    validations:
      required: true
  
  - type: textarea
    id: expected
    attributes:
      label: Comportamento Esperado
      description: O que você esperava que acontecesse?
    validations:
      required: true
  
  - type: textarea
    id: actual
    attributes:
      label: Comportamento Atual
      description: O que realmente aconteceu?
    validations:
      required: true
  
  - type: textarea
    id: code
    attributes:
      label: Código de Exemplo
      description: Se possível, forneça um exemplo mínimo de código que reproduz o problema
      render: csharp
      placeholder: |
        public class Source { public string Name { get; set; } }
        public class Dest { public string Name { get; set; } }
        
        var mapper = new Mapper();
        var result = mapper.Map<Source, Dest>(source);

  - type: textarea
    id: error
    attributes:
      label: Mensagem de Erro
      description: Cole a mensagem de erro completa, stack trace, ou compilation errors
      render: shell

  - type: input
    id: version
    attributes:
      label: Versão do BindMapper
      description: Qual versão do BindMapper você está usando?
      placeholder: ex. 1.1.2
    validations:
      required: true

  - type: dropdown
    id: dotnet-version
    attributes:
      label: Versão do .NET
      description: Qual versão do .NET você está usando?
      options:
        - .NET 6.0
        - .NET 8.0
        - .NET 9.0
        - .NET 10.0
        - Outro
    validations:
      required: true

  - type: input
    id: os
    attributes:
      label: Sistema Operacional
      description: Qual sistema operacional você está usando?
      placeholder: ex. Windows 11, Ubuntu 22.04, macOS 13

  - type: textarea
    id: additional
    attributes:
      label: Informações Adicionais
      description: Qualquer outra informação relevante sobre o problema

  - type: checkboxes
    id: terms
    attributes:
      label: Checklist
      options:
        - label: Procurei por issues similares e não encontrei nenhuma
          required: true
        - label: Estou usando a versão mais recente do BindMapper
          required: false
        - label: Testei com código mínimo reproduzível
          required: false

