name: ✨ Feature Request
description: Sugerir uma nova funcionalidade ou melhoria
title: "[Feature]: "
labels: ["enhancement", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        Obrigado por sugerir uma nova feature! Por favor, descreva sua ideia abaixo.
  
  - type: textarea
    id: problem
    attributes:
      label: Problema ou Necessidade
      description: Existe algum problema que você está tentando resolver? Descreva o contexto.
      placeholder: Eu sempre tenho frustração quando...
    validations:
      required: true
  
  - type: textarea
    id: solution
    attributes:
      label: Solução Proposta
      description: Descreva a solução ou feature que você gostaria de ver
      placeholder: Eu gostaria de poder...
    validations:
      required: true
  
  - type: textarea
    id: alternatives
    attributes:
      label: Alternativas Consideradas
      description: Você considerou alguma solução alternativa?
      placeholder: Tentei usar X, mas...

  - type: textarea
    id: example
    attributes:
      label: Exemplo de Uso
      description: Como você imaginaria usando essa feature?
      render: csharp
      placeholder: |
        // Código de exemplo mostrando como a feature seria usada
        mapper.MapWithCustomLogic<Source, Dest>(source, options => {
            // sua ideia aqui
        });

  - type: dropdown
    id: breaking
    attributes:
      label: É uma Breaking Change?
      description: Essa feature quebraria compatibilidade com código existente?
      options:
        - Não
        - Sim
        - Não tenho certeza
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: Prioridade (na sua opinião)
      options:
        - Baixa (nice to have)
        - Média (seria útil)
        - Alta (impacto significativo)
        - Crítica (bloqueador)

  - type: textarea
    id: benefits
    attributes:
      label: Benefícios
      description: Quais seriam os benefícios dessa feature?
      placeholder: |
        - Melhor performance em cenário X
        - Código mais limpo
        - Suporte a caso de uso Y

  - type: textarea
    id: additional
    attributes:
      label: Informações Adicionais
      description: Qualquer contexto adicional, screenshots, ou referências

  - type: checkboxes
    id: terms
    attributes:
      label: Checklist
      options:
        - label: Procurei por feature requests similares
          required: true
        - label: Essa feature é compatível com os objetivos do projeto (performance, compile-time)
          required: true
        - label: Estou disposto a ajudar implementando (opcional)
          required: false

